# Dissimilarity Binary Symetric ( Tugas 1 )
Penambangan Data

Nama : Okhi Sahrul Barkah

NIM  : 210411100112

**Link Google Colaboratory for play this Code :**

https://colab.research.google.com/drive/1IldbSPMFptGtdMycJ34vuuFVgUHiejF1

In [1]:
import pandas as pd
import numpy as np
studentdata = pd.read_csv('https://gist.githubusercontent.com/khikisb/11c2af1da19ba7894e9e5293877c59c2/raw/a2e2f5e620dbb534dc00182418c2a6b8462de0c6/Data%2520Student')
studentdata

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
# Show all columns from dataframe
studentdata.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

### Kita seleksi Fitur


*   Gender
*   Lunch

In [ ]:
studentdata[['gender', 'lunch']].head(5)

   gender         lunch
0  female      standard
1  female      standard
2  female      standard
3    male  free/reduced
4    male      standard

Change Values to 1/0
Take all values of â€˜gender'

If values is Female change to 1

If values is Male to 0

In [ ]:
# Gender code
gender_female = "female"
gender_male = "male"

# binary value
value_one = 1
value_zero = 0

def change_gender_to_binary(gender):
    return value_one if gender == gender_male else value_zero

Change Values to 1/0
Take all values of â€˜lunch'

If values is Paid change to 1

If values is free to 0

In [ ]:
# lunch code
paid_lunch = "standart"
free_lunch = "free/reduced"

# binary value
value_one = 1
value_zero = 0

def change_lunch_to_binary(lunch):
    return value_one if lunch == free_lunch else value_zero

In [ ]:
# Update all values
studentdata["gender"] = studentdata["gender"].apply(change_gender_to_binary)
studentdata["lunch"] = studentdata["lunch"].apply(change_lunch_to_binary)

In [ ]:
studentdata[['gender', 'lunch']].head(5)

   gender  lunch
0       0      0
1       0      0
2       0      0
3       1      1
4       1      0

In [ ]:
# CONSTAN VARIABLE
DECREMENT_BY_ONE = 1
INCREMENT_BY_ONE = 1

PROBALITY_TABLE_VALUE = {
    "q" : (1,1),
    "r" : (1,0),
    "s" : (0,1),
    "t" : (0,0),
}

In [ ]:
def get_series(studentdata, idx, series):
    return studentdata.loc[(idx), series]

In [ ]:
def dissimilarity_dataset(studentdata, series_index = [], series = []):
    first_series = get_series(studentdata, series_index[0], series)
    second_series = get_series(studentdata, series_index[1], series)
    dataset = pd.concat([first_series,second_series],axis=1)
    return dataset.T

In [ ]:
dissimilarity_dataset(studentdata, [1,2], ["gender", "lunch"]).T

        1  2
gender  0  0
lunch   0  0

In [ ]:
studentdata.loc[0:4, ["gender", "lunch"]]

   gender  lunch
0       0      0
1       0      0
2       0      0
3       1      1
4       1      0

In [ ]:
def count_probality_value(studentdata, start_index = 0, last_index = 1):

    PROBALITY_VALUE = {"q" : 0, "r" : 0, "s" : 0, "t" : 0}

    column_range = studentdata.shape[1]

    for column in range(column_range):
        for value in PROBALITY_TABLE_VALUE:
            item = list((tuple(studentdata.loc[(start_index):(last_index), studentdata.columns[column]]) == PROBALITY_TABLE_VALUE[value], value))
            if item[0] == True:
                if item[1] == "q":
                    PROBALITY_VALUE["q"] += 1
                if item[1] == "r":
                    PROBALITY_VALUE["r"] += 1
                if item[1] == "s":
                    PROBALITY_VALUE["s"] += 1
                if item[1] == "t":
                    PROBALITY_VALUE["t"] += 1

    return PROBALITY_VALUE

In [ ]:
# dimensi (1,2)
dimensi_1_2 = dissimilarity_dataset(studentdata, [1,2], ["gender", "lunch"])

In [ ]:
probality_d_1_2 = count_probality_value(dimensi_1_2, 1, 2)

In [ ]:
# dimensi (1,3)
dimensi_1_3 = dissimilarity_dataset(studentdata, [1,3], ["gender", "lunch"])

In [ ]:
probality_d_1_3 = count_probality_value(dimensi_1_3, 1, 3)

In [ ]:
# dimensi (1,4)
dimensi_1_4 = dissimilarity_dataset(studentdata, [1,4], ["gender", "lunch"])

In [ ]:
probality_d_1_4 = count_probality_value(dimensi_1_4, 1, 4)

### Dissimilarity Binary Symetric Value Formula

---



$$
\frac{r + s}{q + r + s + t}\
$$

In [ ]:
def dissimilarity_binary_symetric_distance(probality_value):
  
    return (probality_value["r"] + probality_value["s"]) / (probality_value["q"] + probality_value["r"] + probality_value["s"] + probality_value["t"])

In [ ]:
dimensi_1_2 = dissimilarity_binary_symetric_distance(probality_d_1_2)
dimensi_1_3 = dissimilarity_binary_symetric_distance(probality_d_1_3)
dimensi_1_4 = dissimilarity_binary_symetric_distance(probality_d_1_4)

In [ ]:
#d1 dan d2

dimensi_1_2

0.0

In [ ]:
# d1 dan d4

dimensi_1_3

1.0

In [ ]:
# d1 dan d4

dimensi_1_4

0.5